import Head from 'next/head'
import NewCarousel from "./Component/Carousel";

export default function Home() {
  return (
    <div>
      <Head>
        <title>LIFE CHOICE GLOBAL RESOURCES SERVICES LTD</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NewCarousel />
    </div>
  )
}
